import os
import json
import logging
from pydantic import BaseModel, Field
from typing import List, Optional

class CQMultiple(BaseModel):
    clarification_questions: List[str] = Field(description="list of clarification questions generated by LLM.")

class CQCoTMultiple(BaseModel):
    reasoning: str = Field(description="analysis about why the query is ambiguous and how LLM proposes to clarify by asking queries.")
    clarification_questions: List[str] = Field(description="list of clarification questions generated by LLM.")

class RQMultiple(BaseModel):
    reformulated_queries: List[str] = Field(description="list of reformulated queries generated by LLM.")

class RQCoTMultiple(BaseModel):
    reasoning: str = Field(description="analysis about why the query is ambiguous and how LLM proposes to clarify by proposing reformulated queries.")
    reformulated_queries: List[str] = Field(description="list of reformulated queries generated by LLM.")

class CQSingle(BaseModel):
    clarification_question: str = Field(description="list of clarification questions generated by LLM.")

class CQCoTSingle(BaseModel):
    reasoning: str = Field(description="analysis about why the query is ambiguous and how LLM proposes to clarify.")
    clarification_question: str = Field(description="list of clarification questions generated by LLM.")

